os: osx
language: c++
before_install:
  - brew update
  - brew bundle
  - brew uninstall libjpeg --ignore-dependencies
  - git config --local user.name "test"
  - git config --local user.email "test@test.de"
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
script: 
  - xcodebuild
  - ls -al build
  - ls -al build/Release
  - ls -al build/Release/EndlessSky.app
deploy:
  provider: releases
  edge:
    branch: ci-releases_debug
  api_key: $GITHUB_TOKEN
  file:
    - build/Release/EndlessSky.app
  skip_cleanup: true
  on:
    repo: iriberri/endless-sky-osx
    branch: master
